"""
Payment Risk Sieve - CLAUDE.md §8.

Logistic Regression model trained on observable customer features only.
Produces payment_failure_probability in [0.0, 1.0].

Observable-only invariant: training data comes from extract_observable(),
not from CustomerLatentState or PotentialOutcomes.

Model lifecycle:
  1. RiskPredictor.build() - train on synthetic observable data (seed=42, 3000 cohort)
  2. RiskPredictor.predict(obs, reference_date) - score a customer
  3. RiskPredictor.explain(features) - top 3 observable signals
"""
from __future__ import annotations

import threading
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import ClassVar

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

from app.risk.features import FEATURE_NAMES, FeatureBuilder, RiskFeatures


# Fixed reference date used during training so the model is reproducible
# across restarts regardless of wall-clock time.
TRAINING_REFERENCE_DATE = datetime(2026, 1, 1, tzinfo=timezone.utc)

MODEL_VERSION = "logistic-v1"


# ── Output types ──────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class RiskSignal:
    feature: str
    impact: float   # signed: positive → increases risk, negative → decreases


@dataclass(frozen=True)
class RiskPrediction:
    risk_score: float           # P(payment_failure) in [0.0, 1.0]
    risk_level: str             # LOW | MEDIUM | HIGH
    top_signals: list[RiskSignal]   # top 3 observable features by impact magnitude
    model_version: str


def _score_to_level(score: float) -> str:
    if score < 0.30:
        return "LOW"
    if score < 0.60:
        return "MEDIUM"
    return "HIGH"


def _observable_risk_label(f: RiskFeatures) -> int:
    """
    Training label derived entirely from observable payment history.
    A customer is labelled 'at risk' (1) when observable signals indicate
    payment difficulty. Never uses latent state.
    """
    if f.payment_success_rate < 0.75:
        return 1
    if f.previous_payment_failures >= 2:
        return 1
    if f.previous_payment_failures >= 1 and f.average_payment_delay > 0.15:
        return 1
    return 0


# ── Risk predictor ────────────────────────────────────────────────────────────

class RiskPredictor:
    """
    Trained Logistic Regression predictor.

    Instantiated via RiskPredictor.build().  Use the module-level
    get_risk_predictor() to obtain the singleton.
    """

    def __init__(self, model: LogisticRegression, scaler: StandardScaler) -> None:
        self._model = model
        self._scaler = scaler

    # ── Training ──────────────────────────────────────────────────────────────

    @classmethod
    def build(
        cls,
        seed: int = 42,
        cohort_size: int = 3000,
        reference_date: datetime = TRAINING_REFERENCE_DATE,
    ) -> "RiskPredictor":
        """
        Train on observable data generated by the simulator.

        The observable boundary is enforced by extract_observable():
        CustomerLatentState and PotentialOutcomes never reach this method.
        """
        # Import here to avoid circular dependency at module level
        from app.simulator.generator import generate_world
        from app.simulator.world import WorldInternal, extract_observable

        raw = generate_world(
            seed=seed,
            cohort_size=cohort_size,
            simulator_version="v1",
            reference_date=reference_date,
        )
        world = WorldInternal.from_raw_records(
            raw=raw,
            seed=seed,
            cohort_size=cohort_size,
            simulator_version="v1",
            reference_date=reference_date,
        )
        obs_world = extract_observable(world)  # isolation guaranteed

        builder = FeatureBuilder(reference_date=reference_date)
        X_rows: list[list[float]] = []
        y_rows: list[int] = []
        for obs in obs_world.customers:
            feat = builder.build(obs)
            X_rows.append(feat.to_array())
            y_rows.append(_observable_risk_label(feat))

        X = np.array(X_rows, dtype=float)
        y = np.array(y_rows, dtype=int)

        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)

        lr = LogisticRegression(random_state=seed, max_iter=1000, C=1.0)
        lr.fit(X_scaled, y)

        return cls(model=lr, scaler=scaler)

    # ── Prediction ────────────────────────────────────────────────────────────

    def predict(
        self,
        obs,  # ObservableCustomerData
        reference_date: datetime | None = None,
    ) -> RiskPrediction:
        """Score one observable customer. Never receives hidden state."""
        ref = reference_date or datetime.now(timezone.utc)
        builder = FeatureBuilder(reference_date=ref)
        features = builder.build(obs)
        return self.predict_from_features(features)

    def predict_from_features(self, features: RiskFeatures) -> RiskPrediction:
        arr = np.array(features.to_array(), dtype=float).reshape(1, -1)
        arr_scaled = self._scaler.transform(arr)
        prob = float(self._model.predict_proba(arr_scaled)[0, 1])
        prob = max(0.0, min(1.0, prob))   # clamp for safety
        return RiskPrediction(
            risk_score=prob,
            risk_level=_score_to_level(prob),
            top_signals=self._explain(features),
            model_version=MODEL_VERSION,
        )

    # ── Explainability ────────────────────────────────────────────────────────

    def _explain(self, features: RiskFeatures) -> list[RiskSignal]:
        """
        Top 3 observable risk signals by magnitude.

        Method: coefficient × scaled_feature_value.
        Fully deterministic and derived from the model and observable features.
        The LLM does NOT participate in risk explanation (CLAUDE.md §13 / §26).
        """
        arr = np.array(features.to_array(), dtype=float).reshape(1, -1)
        arr_scaled = self._scaler.transform(arr)[0]
        contributions = self._model.coef_[0] * arr_scaled
        top_indices = np.argsort(np.abs(contributions))[::-1][:3]
        return [
            RiskSignal(
                feature=FEATURE_NAMES[i],
                impact=float(contributions[i]),
            )
            for i in top_indices
        ]


# ── Module-level singleton ────────────────────────────────────────────────────

_predictor_instance: RiskPredictor | None = None
_predictor_lock = threading.Lock()


def get_risk_predictor() -> RiskPredictor:
    """Lazy singleton: trained once per process, cached for all requests."""
    global _predictor_instance
    if _predictor_instance is None:
        with _predictor_lock:
            if _predictor_instance is None:
                _predictor_instance = RiskPredictor.build()
    return _predictor_instance
